# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
Park.create(name: 'Red Bud Isle', location: '3401 Redbud Trail, Austin, TX 78746', description: 'Red Bud Isle is a popular leash-free dog park that offers a little bit of everything. With over 13 acres located off Redbud Trail near the Tom Miller Dam; one can fish, hike, bike, swim and much more.')
Park.create(name: 'Barkin Springs', location: '2201 Barton Springs Rd, Austin, TX 78746', description: 'Barkin’ Springs is the wading area right outside of Barton Springs that does not require an entrance fee and is a local favorite to take pets to cool off during a hot day. Also, be careful not to confuse Barkin’ Springs with Barking Springs Dog Ranch, a wonderful Dog Ranch located in Del Valle.')
Park.create(name: 'Barton Creek Greenbelt', location: '3755 S Capital of Texas Hwy B, Austin, TX 78704', description: 'Barton Creek Greenbelt is 7.9 miles long, covering 809 acres. The trail has entrances at different locations around Austin and is a perfect spot to take your dog on a long walk through natural scenery. A leash is required for all pets and tennis shoes and/or a bathing suit for humans is recommended to cool off in the creek areas!')
Park.create(name: 'Bob Wentz Park', location: '7144 Comanche Trail, Austin, TX 78732', description: 'Only a 30 minute drive from downtown Austin, Bob Wentz Park on Lake Travis is a waterfront, natural grass lawn to take your beloved pet to on a sunny day. The park does require all pets to be on a leash and they are not permitted on The Point, a shoreline area of the park.')
Park.create(name: 'Norwood Estate Dog Park', location: '1009 Edgecliff Terrace, Austin, TX 78704', description: 'Located on East Riverside Dr. and near I-35, Norwood Estate Dog Park is a 5+ acre park surrounded by gates and has a section for large dogs and small dogs.')
Park.create(name: 'Bull Creek Districk Park', location: '6701 Lakewood Dr, Austin, TX 78731', description: 'Bull Creek District Park is over 32 square miles of protected, tended to terrain with a natural swimming area for all, scenic cliffs and ')
Park.create(name: 'Emma Long Metropolitan Park', location: '1600 City Park Rd, Austin, TX 78730', description: 'Emma Long Metropolitan Park is one of the largest parks in Austin, offering camping sites, trails, lake front swimming and much more. Dogs are required on leash but there are plenty of things to do with them while you explore the expansive park.')
Park.create(name: 'Onion Creek District Park', location: '7002 Onion Creek Dr, Austin, TX 78744', description: 'Located in Southeast Austin and covering 179 acres, Onion Creek District Park is a little-known park that is perfect place for your pet. Most of the park is off-leash and offers areas for animals to swim and venture through the shady hiking trails.')
Park.create(name: 'Shoal Creek Greenbelt', location: '2600 N Lamar Blvd, Austin, TX 78705', description: 'Only about 10 minutes from downtown Austin and near the University of Texas campus, Shoal Creek Greenbelt is 76 acres of scenic trails. The trail requires a leash on dogs, except from 24th Street to 29th Street.')
Park.create(name: 'Walnut Creek Metropolitan Park', location: '12138 N Lamar Blvd, Austin, TX 78753', description: 'Walnut Creek Metropolitan Park is 293 acres of hike-and-bike trails that offers an off-leash area. The trails are hilly, meandering trails that are very popular for mountain bikers, so be careful if your dog is skittish of bicyclist.')
Park.create(name: 'Bee Cave Dog Park', location: '13676 Bee Cave Pkwy, Bee Cave, TX 78738', description: 'The park has a small pond, doesn’t require dogs to wear leashes, and is a short walk away from the Bee Cave Central Park.')
Park.create(name: 'West Austin Park & Wading Pool', location: '1317 W 10th St, Austin, TX 78703', description: 'Situated in the middle of historic Clarksville, West Austin Park is 3 acre park. Within the park is basketball courts, picnic tables, tennis courts and of course a fenced off-leash dog area.')
Park.create(name: 'Mary Moore Searight Metropolitan Park', location: '907 West Slaughter Lane, Austin, TX 78748', description: 'Mary Moore Searight Metropolitan Park is located a little over 10 miles away from Dowtown Austin but well worth the drive! From disc golf, horseback trails, a playground to volleyball and tennis courts, plus an off-leash dog area. This is a place you must visit at least once')
Park.create(name: 'Yard Bar', location: '6700 Burnet Rd, Austin, TX 78757', description: 'This dog-friendly hangout offers space for dogs to play but has an adjoining bar with dining area for the humans. Toys and water bowls help keep a four-legged companion happy, while craft beers, cocktails or yummy food can be purchased for the two-legged owner.')
Park.create(name: 'Cedar Bark Park', location: '2525 W New Hope Dr, Cedar Park, TX 78613', description: 'Located in Veterans Memorial Park, Cedar Bark Park is a 5-acre fenced in dog park. Amenities include a natural dog pond, pet waste stations, benches, drinking fountains, dog showers and natural features.')
Park.create(name: 'Auditorium Shores', location: '900 W Riverside Dr, Austin, TX 78704', description: 'Auditorium Shores offers an off-leash dog park with amazing views of the Austin skyline and famous Stevie Ray Vaughan statue. However, the park is not fenced and close to the street so pet owners should be cautious of their animals whereabouts.')
Park.create(name: 'Ann and Roy Butler Hike-and-Bike Trail Boardwalk', location: 'Ann and Roy Butler Hike and Bike Trail, Austin, TX', description: 'Formally known as the Town Lake/Lady Bird Lake Hike-and-Bike trail, over 1.5 million people visit this 10+ mile trail every year. Dogs are welcome to accompany their owners on this trail but all must be on a short leash.')
Park.create(name: 'Zilker Metropolitan Park', location: '2100 Barton Springs Rd, Austin, TX 78704', description: 'Zilker Park is a popular recreational area, hosting events like Austin City Limits and the Trail of Lights. When an event isn’t going on at Zilker Park, there are over 350 acres of grassy terrain for a dog to play and run its little furry tail off')
